import React from "react";
import "./App.css"; // Ensure this imports your main CSS file

// Catalogue Data
const tentCatalog = [
  {
    id: 1,
    name: "The Obsidian Marquee",
    tier: "Platinum Collection",
    capacity: "Up to 500 Guests",
    features: "Clearspan, Integrated Flooring, Climate Control",
    image: "/image/tent1.jpg", // Replace with your image paths
  },
  {
    id: 2,
    name: "Aurora Sailcloth",
    tier: "Signature Series",
    capacity: "100 - 300 Guests",
    features: "Translucent fabric, Natural wood poles, Ethereal glow",
    image: "/image/tent2.jpg",
  },
  {
    id: 3,
    name: "Mirage Stretch Structure",
    tier: "Bespoke Concepts",
    capacity: "Flexible configurations",
    features: "Aerodynamic design, Any-terrain setup, Ambient lighting",
    image: "/image/tent3.jpg",
  },
  {
    id: 4,
    name: "Celestial Pagoda",
    tier: "Boutique Events",
    capacity: "50 - 100 Guests",
    features: "High-peak, Elegant curves, Perfect for VIP lounges",
    image: "/image/tent4.jpg", // Added a 4th for a fuller grid
  }
];

const Tents = () => (
  <section className="glass-tents-section" id="tents">
    {/* Abstract shapes generated by CSS for the glass to blur over */}
    <div className="abstract-blob blob-1"></div>
    <div className="abstract-blob blob-2"></div>

    <div className="glass-content-container">
      <header className="catalog-header">
        <span className="premium-tag">Premium Event Enclosures</span>
        <h2 className="catalog-title">Architectural Tents</h2>
        <p className="catalog-subtitle">
          Discover our curated collection of world-class temporary structures, 
          designed to transform any location into a luxurious venue.
        </p>
      </header>

      <div className="glass-grid">
        {tentCatalog.map((tent) => (
          <div key={tent.id} className="glass-card">
            <div className="card-image-wrapper">
              <img src={tent.image} alt={tent.name} className="card-img" />
              <div className="card-gloss-overlay"></div>
            </div>
            <div className="card-content">
              <span className="tent-tier">{tent.tier}</span>
              <h3 className="tent-name">{tent.name}</h3>
              
              <div className="tent-details">
                <p><strong>Capacity:</strong> {tent.capacity}</p>
                <p><strong>Key Features:</strong> {tent.features}</p>
              </div>

              <div className="card-actions">
                <button className="btn-secondary">Details</button>
                <button className="btn-primary">Reserve</button>
              </div>
            </div>
          </div>
        ))}
      </div>

      <footer className="catalog-footer">
        <div className="service-glass-panel">
          <p>Complete White-Glove Service: Consult, Design, Install, & Support.</p>
          <button className="btn-contact">Contact Planner</button>
        </div>
      </footer>
    </div>
  </section>
);

export default Tents;